version: "3.4"

services:
  mysql:
    image: mysql:latest
    restart: ${RESTART}
    ports:
      - ${PORT}:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: ${RESTART}
    depends_on:
      - db
    ports:
      - ${PHPADMIN_PORT}:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORT: ${ROOT_PASSWORD}

volumes:
  mysql-data:
