version: "3.4"

services:
  rabbitmq:
    image: rabbitmq:management
    restart: ${RESTART}
    environment:
      RABBITMQ_DEFAULT_USER: ${USERNAME}
      RABBITMQ_DEFAULT_PASS: ${PASSWORD}
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
   rabbitmq-data: