version: "3.4"

services:
  mongo:
    image: mongo:latest
    restart: ${RESTART}
    ports:
      - ${PORT}:27017
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_ROOT_USERNAME=${ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${ROOT_PASSWORD}

volumes:
  mongo-data:
